[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["**/__pycache__", ".venv", ".mypy_cache", "dist", "build"]

[tool.ruff.lint]
# Keep the signal, drop the noise.
# - E/F: core errors (pycodestyle/pyflakes)
# - I: import sorting
# - UP: safe modernizations (pyupgrade)
select = ["E", "F", "I", "UP"]

# No line-length linting; formatter still wraps at 100 if needed.
ignore = ["E501"]

# Let Ruff auto-fix what it can.
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
