[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["**/__pycache__", ".venv", ".mypy_cache", "dist", "build"]

[tool.ruff.lint]
# Strict but practical. We silence line-length (E501) by default.
select = ["E","F","W","I","UP","B","C4","N","C90","D","ANN","RUF"]
ignore = ["E501","D203","D213","ANN101","ANN102"]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
