[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["**/__pycache__", ".venv", ".mypy_cache", "dist", "build"]

[tool.ruff.lint]
# Keep this strict; it matches your “always type” preference.
select = ["E","F","W","I","UP","B","C4","N","C90","D","ANN","RUF"]
ignore = ["D203","D213","ANN101","ANN102"]  # docstring newline prefs; allow missing self/cls
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
